<?php

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
  public function run()
  {
    $users = [
      [
        'id'                => 1,
        'name'              => 'Admin',
        'address'           => 'Inkılap Mah.',
        'email'             => 'ogur.uyanik13@gmail.com',
        'phone'             => '9052456134513',
        'user_ref_number'   => '000000',
        'user_total_debt'   => '0',
        'email_verified_at' =>  Carbon::now(),
        'password'          => '$2y$10$ot.An./kAR2Fw.jklRebs.dtaUoELiIhX568gw/grw0NUG1jOvBFi',
        'remember_token'    => null,
        'role'              => 'admin',
        'created_at'        => '2019-04-15 19:13:32',
        'updated_at'        => '2019-04-15 19:13:32',
        'deleted_at'        => null,
      ],
//      [
//        'id'                => 2,
//        'name'              => 'TEST STORE',
//        'address'           => 'Inkılap Mah.',
//        'email'             => 'store@store.com',
//        'phone'             => '9052456134519',
//        'user_ref_number'   => '000000',
//        'user_total_debt'   => '0',
//        'email_verified_at' =>  Carbon::now(),
//        'password'          => '$2y$10$ot.An./kAR2Fw.jklRebs.dtaUoELiIhX568gw/grw0NUG1jOvBFi',
//        'remember_token'    => null,
//        'role'              => 'store',
//        'created_at'        => '2019-04-15 19:13:32',
//        'updated_at'        => '2019-04-15 19:13:32',
//        'deleted_at'        => null,
//      ],
//      [
//        'id'                => 3,
//        'name'              => 'ATEST USER',
//        'address'           => 'Inkılap Mah.',
//        'email'             => 'user@user.com',
//        'phone'             => '9052456134518',
//        'user_ref_number'   => '000001',
//        'user_total_debt'   => '187',
//        'email_verified_at' =>  Carbon::now(),
//        'password'          => '$2y$10$ot.An./kAR2Fw.jklRebs.dtaUoELiIhX568gw/grw0NUG1jOvBFi',
//        'remember_token'    => null,
//        'role'              => 'user',
//        'created_at'        => '2019-04-15 19:13:32',
//        'updated_at'        => '2019-04-15 19:13:32',
//        'deleted_at'        => null,
//      ],
//      [
//        'id'                => 4,
//        'name'              => 'BTEST USER',
//        'address'           => 'Inkılap Mah.',
//        'email'             => 'buser@user.com',
//        'phone'             => '90524561345124',
//        'user_ref_number'   => '000001',
//        'user_total_debt'   => '468',
//        'email_verified_at' =>  Carbon::now(),
//        'password'          => '$2y$10$ot.An./kAR2Fw.jklRebs.dtaUoELiIhX568gw/grw0NUG1jOvBFi',
//        'remember_token'    => null,
//        'role'              => 'user',
//        'created_at'        => '2019-04-15 19:13:32',
//        'updated_at'        => '2019-04-15 19:13:32',
//        'deleted_at'        => null,
//      ],
//      [
//        'id'                => 5,
//        'name'              => 'CTEST USER',
//        'address'           => 'Inkılap Mah.',
//        'email'             => 'cuser@user.com',
//        'phone'             => '9152456134528',
//        'user_ref_number'   => '000001',
//        'user_total_debt'   => '748',
//        'email_verified_at' =>  Carbon::now(),
//        'password'          => '$2y$10$ot.An./kAR2Fw.jklRebs.dtaUoELiIhX568gw/grw0NUG1jOvBFi',
//        'remember_token'    => null,
//        'role'              => 'user',
//        'created_at'        => '2019-04-15 19:13:32',
//        'updated_at'        => '2019-04-15 19:13:32',
//        'deleted_at'        => null,
//      ],
//      [
//        'id'                => 6,
//        'name'              => 'DTEST USER',
//        'address'           => 'Inkılap Mah.',
//        'email'             => 'duser@user.com',
//        'phone'             => '9052436137528',
//        'user_ref_number'   => '000001',
//        'user_total_debt'   => '659',
//        'email_verified_at' =>  Carbon::now(),
//        'password'          => '$2y$10$ot.An./kAR2Fw.jklRebs.dtaUoELiIhX568gw/grw0NUG1jOvBFi',
//        'remember_token'    => null,
//        'role'              => 'user',
//        'created_at'        => '2019-04-15 19:13:32',
//        'updated_at'        => '2019-04-15 19:13:32',
//        'deleted_at'        => null,
//      ],
//      [
//        'id'                => 7,
//        'name'              => 'ETEST USER',
//        'address'           => 'Inkılap Mah.',
//        'email'             => 'euser@user.com',
//        'phone'             => '9052856134528',
//        'user_ref_number'   => '000001',
//        'user_total_debt'   => '89',
//        'email_verified_at' =>  Carbon::now(),
//        'password'          => '$2y$10$ot.An./kAR2Fw.jklRebs.dtaUoELiIhX568gw/grw0NUG1jOvBFi',
//        'remember_token'    => null,
//        'role'              => 'user',
//        'created_at'        => '2019-04-15 19:13:32',
//        'updated_at'        => '2019-04-15 19:13:32',
//        'deleted_at'        => null,
//      ],
//      [
//        'id'                => 8,
//        'name'              => 'FTEST USER',
//        'address'           => 'Inkılap Mah.',
//        'email'             => 'Fuser@user.com',
//        'phone'             => '9052456134528',
//        'user_ref_number'   => '000001',
//        'user_total_debt'   => '396',
//        'email_verified_at' =>  Carbon::now(),
//        'password'          => '$2y$10$ot.An./kAR2Fw.jklRebs.dtaUoELiIhX568gw/grw0NUG1jOvBFi',
//        'remember_token'    => null,
//        'role'              => 'user',
//        'created_at'        => '2019-04-15 19:13:32',
//        'updated_at'        => '2019-04-15 19:13:32',
//        'deleted_at'        => null,
//      ],
//      [
//        'id'                => 9,
//        'name'              => 'GTEST USER',
//        'address'           => 'Inkılap Mah.',
//        'email'             => 'guser@user.com',
//        'phone'             => '9052456138628',
//        'user_ref_number'   => '000001',
//        'user_total_debt'   => '168',
//        'email_verified_at' =>  Carbon::now(),
//        'password'          => '$2y$10$ot.An./kAR2Fw.jklRebs.dtaUoELiIhX568gw/grw0NUG1jOvBFi',
//        'remember_token'    => null,
//        'role'              => 'user',
//        'created_at'        => '2019-04-15 19:13:32',
//        'updated_at'        => '2019-04-15 19:13:32',
//        'deleted_at'        => null,
//      ],
//      [
//        'id'                => 10,
//        'name'              => 'HTEST USER',
//        'address'           => 'Inkılap Mah.',
//        'email'             => 'Huser@user.com',
//        'phone'             => '9058456124528',
//        'user_ref_number'   => '000001',
//        'user_total_debt'   => '473',
//        'email_verified_at' =>  Carbon::now(),
//        'password'          => '$2y$10$ot.An./kAR2Fw.jklRebs.dtaUoELiIhX568gw/grw0NUG1jOvBFi',
//        'remember_token'    => null,
//        'role'              => 'user',
//        'created_at'        => '2019-04-15 19:13:32',
//        'updated_at'        => '2019-04-15 19:13:32',
//        'deleted_at'        => null,
//      ],
    ];

    User::insert($users);
  }
}
